# Generated by Django 6.0 on 2025-12-10 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='registered_courses',
            field=models.ManyToManyField(blank=True, related_name='participants', to='main_app.course'),
        ),
        migrations.AddField(
            model_name='person',
            name='registered_events',
            field=models.ManyToManyField(blank=True, related_name='participants', to='main_app.event'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
