# Generated by Django 6.0 on 2025-12-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_rename_name_person_first_name_person_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='student_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
