# Generated by Django 6.0 on 2025-12-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_person_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='registered_courses',
        ),
        migrations.RemoveField(
            model_name='person',
            name='registered_events',
        ),
    ]
