# Generated by Django 6.0 on 2026-01-01 20:32

import auth_app.models
import auth_app.utils
import datetime
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_remove_person_email_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.validate_integer, auth_app.models.valid_phone_ir])),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('student_id', models.CharField(blank=True, max_length=10, null=True)),
                ('otp', models.CharField(blank=True, default=auth_app.utils.generate_random_otp, max_length=6, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expiration_time', models.DurationField(default=datetime.timedelta(seconds=300))),
                ('revalidation_time', models.DurationField(default=datetime.timedelta(seconds=120))),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
