# Generated by Django 6.0 on 2026-01-01 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_pendingregistration_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='expiration_time',
            field=models.DurationField(default=datetime.timedelta(seconds=900)),
        ),
    ]
