# Generated by Django 6.0 on 2026-01-02 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_alter_pendingregistration_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='expiration_time',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
    ]
