# Generated by Django 6.0 on 2026-02-10 18:39

import auth_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_alter_pendingregistration_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.validate_integer, auth_app.models.valid_phone_ir]),
        ),
    ]
