# Generated by Django 6.0 on 2026-02-10 21:19

import auth_app.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='expiration_time',
            field=models.DurationField(default=datetime.timedelta(seconds=420)),
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.validate_integer, auth_app.models.valid_phone_ir]),
        ),
    ]
