# Generated by Django 6.0 on 2026-02-14 14:02

import auth_app.utils
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_alter_pendingregistration_expiration_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change_verified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PasswordChangeOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, default=auth_app.utils.generate_random_otp, max_length=6, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expiration_time', models.DurationField(default=datetime.timedelta(seconds=660))),
                ('revalidation_time', models.DurationField(default=datetime.timedelta(seconds=120))),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
