# Generated by Django 6.0 on 2026-02-14 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_user_password_change_verified_time_passwordchangeotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordchangeotp',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_change_otp', to=settings.AUTH_USER_MODEL),
        ),
    ]
