# Generated by Django 6.0 on 2026-02-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_alter_passwordchangeotp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_change_verified_time',
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
