# Generated by Django 6.0 on 2025-12-10 13:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=256, null=True, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('registration_start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('registration_deadline', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('registered', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.BigIntegerField(default=0)),
                ('organizer', models.CharField(blank=True, max_length=64, null=True)),
                ('speakers', models.ManyToManyField(blank=True, related_name='events_as_speaker', to='auth_app.person')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.image')),
                ('tags', models.ManyToManyField(related_name='events', to='main_app.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, db_index=True, max_length=256, null=True, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('registration_start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('registration_deadline', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('registered', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.BigIntegerField(default=0)),
                ('organizer', models.CharField(blank=True, max_length=64, null=True)),
                ('instructors', models.ManyToManyField(blank=True, related_name='courses_as_instructor', to='auth_app.person')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.image')),
                ('tags', models.ManyToManyField(related_name='courses', to='main_app.tag')),
            ],
        ),
    ]
