# Generated by Django 6.0 on 2025-12-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_course_image_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('0', 'Saturday'), ('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday')], db_index=True, max_length=11)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='time_plans',
            field=models.ManyToManyField(blank=True, related_name='courses', to='main_app.timeplan'),
        ),
    ]
