# Generated by Django 6.0 on 2025-12-13 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_timeplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeplan',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_plans', to='main_app.course'),
        ),
    ]
