# Generated by Django 6.0 on 2025-12-18 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_course_tags_alter_event_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeplan',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_plans', to='main_app.course'),
        ),
    ]
