# Generated by Django 6.0 on 2025-12-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_remove_person_registered_courses_and_more'),
        ('main_app', '0006_alter_timeplan_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(related_name='registered_%(class)s', to='auth_app.person'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='registered_%(class)s', to='auth_app.person'),
        ),
    ]
