# Generated by Django 6.0 on 2025-12-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_remove_person_registered_courses_and_more'),
        ('main_app', '0007_course_participants_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='registered_%(class)s', to='auth_app.person'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='registered_%(class)s', to='auth_app.person'),
        ),
    ]
