# Generated by Django 6.0 on 2025-12-20 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_remove_person_registered_courses_and_more'),
        ('main_app', '0008_alter_course_participants_alter_event_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.CreateModel(
            name='CourseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.course')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'person'), name='unique_course_person')],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'person'), name='unique_event_person')],
            },
        ),
    ]
