# Generated by Django 6.0 on 2025-12-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_remove_person_registered_courses_and_more'),
        ('main_app', '0009_remove_course_participants_remove_event_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='registered_courses', through='main_app.CourseParticipant', to='auth_app.person'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='registered_events', through='main_app.EventParticipant', to='auth_app.person'),
        ),
    ]
