# Generated by Django 6.0 on 2025-12-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_course_is_active_event_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dependencies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='dependencies',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
