# Generated by Django 6.0 on 2025-12-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_course_dependencies_event_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_full',
            field=models.BooleanField(default=False),
        ),
    ]
