# Generated by Django 6.0 on 2025-12-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_course_is_full_event_is_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseparticipant',
            name='email_at_registration',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='courseparticipant',
            name='first_name_at_registration',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='courseparticipant',
            name='last_name_at_registration',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='courseparticipant',
            name='phone_at_registration',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='courseparticipant',
            name='student_id_at_registration',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='email_at_registration',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='first_name_at_registration',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='last_name_at_registration',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='phone_at_registration',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='student_id_at_registration',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
