# Generated by Django 6.0 on 2025-12-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_courseparticipant_email_at_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseparticipant',
            name='status',
            field=models.CharField(choices=[('accepted', 'تایید  شده'), ('pending', 'در حال پردازش'), ('cancelled', 'لغو شده')], default='accepted', max_length=20),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('accepted', 'تایید  شده'), ('pending', 'در حال پردازش'), ('cancelled', 'لغو شده')], default='accepted', max_length=20),
        ),
    ]
