# Generated by Django 6.0 on 2026-02-22 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0018_user_token_version'),
        ('main_app', '0015_courseparticipant_status_eventparticipant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseparticipant',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_participants', to='auth_app.person'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participants', to='auth_app.person'),
        ),
    ]
